Console.WriteLine("Hello, World!");
Console.WriteLine("Line 1");
Console.WriteLine("Line 2");
int[] numbers = { 1, 2, 3 };
double avg = (2 + 4 + 6) / 3.0;
Console.WriteLine(avg);
Console.WriteLine("Main change");
int max = Math.Max(3, 7);
Console.WriteLine(max);
int min = Math.Min(3, 7);
Console.WriteLine(min);
Console.WriteLine("Another main change");